const USER_ACTION_TYPES = {
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  UPDATE_USER: "UPDATE_USER",
  FETCHING_USER: "FETCHING_USER",
  END_OF_FETCHING_USER: "END_OF_FETCHING_USER",
};
export default USER_ACTION_TYPES;
