const USER_ACTION_TYPES = {
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  UPDATE_USER: "UPDATE_USER",
  FETCHING_USER: "FETCHING_USER",
  END_OF_FETCHING_USER: "END_OF_FETCHING_USER",
  ADD_PRODUCT_TO_PURCHASE_LIST: "ADD_PRODUCT_TO_PURCHASE_LIST",
  REMOVE_PRODUCT_FROM_PURCHASE_LIST: "REMOVE_PRODUCT_FROM_PURCHASE_LIST",
};
export default USER_ACTION_TYPES;
